### ISSUE TITLE
Unable to utilize wasm build

### ISSUE THREAD

**Issue by luke-momentusresearch** [artoolkitx/jsartoolkit5#116]
```
artoolkit_wasm.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'buffer')
    at receiveInstance (artoolkit_wasm.js:1:42780)
    at artoolkit_wasm.js:1:873
    at Object.then (artoolkit.debug.js:125794:9)
    at artoolkit_wasm.js:1:807
receiveInstance	@	artoolkit_wasm.js:1
(anonymous)	@	artoolkit_wasm.js:1
then	@	artoolkit.debug.js:125794
(anonymous)	@	artoolkit_wasm.js:1
Promise.then (async)		
Module.instantiateWasm	@	artoolkit_wasm.js:1
createWasm	@	artoolkit_wasm.js:1
(anonymous)	@	artoolkit_wasm.js:1
```

Built using docker instructions as described here:

https://github.com/artoolkitx/jsartoolkit5/issues/113#issuecomment-1090654171

what can I do to resolve this?

Thanks!

**Comment by luke-momentusresearch** [comment]
follow the [simple_image_wasm.html](https://github.com/artoolkitx/jsartoolkit5/blob/master/examples/simple_image_wasm.html) example
